import type { Metadata } from "next";
import { Heebo, Montserrat, Kalam } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const heebo = Heebo({
  subsets: ["latin"],
  variable: '--font-heebo',
  display: 'swap',
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: '--font-montserrat',
  display: 'swap',
});

const kalam = Kalam({
  subsets: ["latin"],
  variable: '--font-kalam',
  weight: "400",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${heebo.variable} ${montserrat.variable} ${kalam.variable}`}>
        <Header />

        <div className={'children'}>
          {children}
        </div>
      </body>
    </html>
  );
}
